### ISSUE TITLE
eslint is missing in devDependencies

### ISSUE THREAD

**Issue by belozer** [bem/bem-react#514]
```
lerna ERR! npm run test stderr:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/sergey/Projects/bem-react/
```

package.json
```
{
  "private": true,
  "scripts": {
    "bootstrap": "lerna bootstrap",
    "lint": "lerna run lint",
    "prepush": "lerna run test",
    "publish:next": "lerna publish --canary --preid dev --npm-tag next --no-git-tag-version"
  },
  "devDependencies": {
    "@commitlint/cli": "7.2.1",
    "@commitlint/config-conventional": "7.1.2",
    "@types/chai": "4.1.7",
    "@types/chai-spies": "1.0.0",
    "@types/enzyme": "3.1.15",
    "@types/mocha": "5.2.5",
    "@types/react": "16.8.8",
    "chai": "4.2.0",
    "chai-spies": "1.0.0",
    "chalk": "2.4.1",
    "enzyme": "3.7.0",
    "enzyme-adapter-react-16": "1.7.0",
    "gzip-size": "5.1.0",
    "husky": "3.0.5",
    "jsdom": "13.0.0",
    "lerna": "3.5.1",
    "lint-staged": "9.2.5",
    "mocha": "5.2.0",
    "nyc": "13.1.0",
    "prettier": "1.18.2",
    "pretty-bytes": "5.2.0",
    "react": "16.8.4",
    "react-dom": "16.8.4",
    "rollup": "1.10.1",
    "rollup-plugin-node-resolve": "4.2.3",
    "rollup-plugin-replace": "2.1.0",
    "rollup-plugin-strip-banner": "0.2.0",
    "rollup-plugin-terser": "4.0.4",
    "rollup-plugin-typescript2": "0.21.0",
    "source-map-support": "0.5.9",
    "ts-node": "7.0.1",
    "tslint": "5.11.0",
    "tslint-react": "3.6.0",
    "typescript": "3.2.1"
  }
}
```

**Comment by yarastqt** [comment]
Чет не могу воспроизвести у себя на чистом репозитории, можешь рассказать флоу как у тебя получается словить это? А так же версию ноды?

**Comment by belozer** [comment]
@yarastqt действительно странно... Пока что-то не удаётся воспроизвести. Хотя до этого стабильно воспроизводилось.

Закрываю issue. Переоткрою, если повторится.
